export const sampleBooks = [
    {
        id: 1,
        title: "A Study in Scarlet",
        author: "Arthur Conan Doyle",
        genre: "Detective",
        publicationYear: 1887,
        cover_image: "https://m.media-amazon.com/images/I/71HMyqG6MRL.jpg",
        description: "The first Sherlock Holmes novel that introduces the legendary detective and Dr. Watson.",
        rating: 4.7,
        reviews: 2300,
        link: "https://www.gutenberg.org/ebooks/244",
        language: "English",
        pages: 123,
        publisher: "Ward Lock & Co",
        isbn: "9781514698986"
    },
    {
        id: 2,
        title: "Pride and Prejudice",
        author: "Jane Austen",
        genre: "Classic Literature",
        publicationYear: 1813,
        cover_image: "https://m.media-amazon.com/images/I/91HHqVTAJQL.jpg",
        description: "A romantic novel that also critiques the British landed gentry at the end of the 18th century.",
        rating: 4.4,
        reviews: 9800,
        link: "https://www.gutenberg.org/ebooks/1342",
        language: "English",
        pages: 279,
        publisher: "T. Egerton",
        isbn: "9780141439518"
    },
    {
        id: 3,
        title: "Atomic Habits",
        author: "James Clear",
        genre: "Self-Help / Productivity",
        publicationYear: 2018,
        cover_image: "https://m.media-amazon.com/images/I/91bYsX41DVL.jpg",
        description: "An easy & proven way to build good habits & break bad ones.",
        rating: 4.8,
        reviews: 95000,
        link: "https://archive.org/details/atomichabitsjame0000clea",
        language: "English",
        pages: 320,
        publisher: "Avery",
        isbn: "9780735211292"
    },
    {
        id: 4,
        title: "The Art of War",
        author: "Sun Tzu",
        genre: "Strategy / Philosophy",
        publicationYear: -500,
        cover_image: "https://m.media-amazon.com/images/I/81WrpVguxdL.jpg",
        description: "An ancient Chinese military treatise offering timeless strategies for warfare and leadership.",
        rating: 4.3,
        reviews: 8000,
        link: "https://www.gutenberg.org/ebooks/132",
        language: "English",
        pages: 68,
        publisher: "Various",
        isbn: "9781599869773"
    },
    {
        id: 5,
        title: "The Adventures of Tom Sawyer",
        author: "Mark Twain",
        genre: "Adventure / Classic",
        publicationYear: 1876,
        cover_image: "https://m.media-amazon.com/images/I/81eqvZC3QlL.jpg",
        description: "The mischievous adventures of a boy growing up along the Mississippi River.",
        rating: 4.2,
        reviews: 7000,
        link: "https://www.gutenberg.org/ebooks/74",
        language: "English",
        pages: 274,
        publisher: "American Publishing Company",
        isbn: "9780486400778"
    },
    {
        id: 6,
        title: "Sapiens: A Brief History of Humankind",
        author: "Yuval Noah Harari",
        genre: "History / Non-Fiction",
        publicationYear: 2011,
        cover_image: "https://m.media-amazon.com/images/I/713jIoMO3UL.jpg",
        description: "A compelling narrative exploring the history and evolution of the human species.",
        rating: 4.7,
        reviews: 75000,
        link: "https://archive.org/details/sapiensbriefhist0000hara",
        language: "English",
        pages: 498,
        publisher: "Harvill Secker",
        isbn: "9780062316097"
    },
    {
        id: 7,
        title: "1984",
        author: "George Orwell",
        genre: "Dystopian / Political Fiction",
        publicationYear: 1949,
        cover_image: "https://m.media-amazon.com/images/I/71kxa1-0mfL.jpg",
        description: "A chilling vision of a totalitarian future under constant surveillance.",
        rating: 4.6,
        reviews: 90000,
        link: "https://archive.org/details/1984_201907",
        language: "English",
        pages: 328,
        publisher: "Secker & Warburg",
        isbn: "9780451524935"
    },
    {
        id: 8,
        title: "Rich Dad Poor Dad",
        author: "Robert T. Kiyosaki",
        genre: "Finance / Self-Help",
        publicationYear: 1997,
        cover_image: "https://m.media-amazon.com/images/I/81bsw6fnUiL.jpg",
        description: "Personal finance advice through the lessons learned from two father figures.",
        rating: 4.5,
        reviews: 67000,
        link: "https://archive.org/details/richdadpoordad00robe",
        language: "English",
        pages: 336,
        publisher: "Warner Books",
        isbn: "9781612680194"
    },
    {
        id: 9,
        title: "To Kill a Mockingbird",
        author: "Harper Lee",
        genre: "Classic / Coming-of-Age",
        publicationYear: 1960,
        cover_image: "https://m.media-amazon.com/images/I/81Ox+R-7tXL.jpg",
        description: "A profound commentary on race and justice in the Deep South, seen through a child's eyes.",
        rating: 4.9,
        reviews: 120000,
        link: "https://archive.org/details/tokillmockingbir0000leep",
        language: "English",
        pages: 324,
        publisher: "J.B. Lippincott & Co.",
        isbn: "9780061120084"
    },
    {
        id: 10,
        title: "The Selfish Gene",
        author: "Richard Dawkins",
        genre: "Science / Evolution",
        publicationYear: 1976,
        cover_image: "https://m.media-amazon.com/images/I/91cTjVb9S1L.jpg",
        description: "A revolutionary look at evolution, arguing genes drive natural selection.",
        rating: 4.6,
        reviews: 4300,
        link: "https://archive.org/details/selfishgene30anni00dawk",
        language: "English",
        pages: 360,
        publisher: "Oxford University Press",
        isbn: "9780198788607"
    }
];
