export const sampleBooks = [
    {
        id: 1,
        title: "The Great Gatsby",
        author: "F. Scott Fitzgerald",
        genre: "Fiction",
        publicationYear: 1925,
        coverImage: "https://m.media-amazon.com/images/I/61mKM5L-TAL._AC_UF1000,1000_QL80_.jpg",
        description: "A novel about the American dream and the disillusionment of the Jazz Age.",
        rating: 4.5,
        reviews: 1200,
        link: 'https://www.planetebook.com/free-ebooks/the-great-gatsby.pdf',
        language: 'English',
        pages: 180,
        publisher: 'Scribner',
        isbn: '9780743273565',
    },
    {
        id: 2,
        title: "The Great Gatsby",
        author: "F. Scott Fitzgerald",
        genre: "Fiction",
        publicationYear: 1925,
        coverImage: "https://m.media-amazon.com/images/I/61mKM5L-TAL._AC_UF1000,1000_QL80_.jpg",
        description: "A novel about the American dream and the disillusionment of the Jazz Age.",
        rating: 4.5,
        reviews: 1200,
        link: 'https://www.planetebook.com/free-ebooks/the-great-gatsby.pdf',
    },
    {
        id: 4,
        title: "The Great Gatsby",
        author: "F. Scott Fitzgerald",
        genre: "Fiction",
        publicationYear: 1925,
        coverImage: "https://m.media-amazon.com/images/I/61mKM5L-TAL._AC_UF1000,1000_QL80_.jpg",
        description: "A novel about the American dream and the disillusionment of the Jazz Age.",
        rating: 4.5,
        reviews: 1200,
        link: 'https://www.planetebook.com/free-ebooks/the-great-gatsby.pdf',
    },
    {
        id: 3,
        title: "The Great Gatsby",
        author: "F. Scott Fitzgerald",
        genre: "Fiction",
        publicationYear: 1925,
        coverImage: "https://m.media-amazon.com/images/I/61mKM5L-TAL._AC_UF1000,1000_QL80_.jpg",
        description: "A novel about the American dream and the disillusionment of the Jazz Age.",
        rating: 4.5,
        reviews: 1200,
        link: 'https://www.planetebook.com/free-ebooks/the-great-gatsby.pdf',
    }
]