export const courses = [
    {
        id: 1,
        thumbnail: ['https://bairesdev.mo.cloudinary.net/blog/2023/08/What-Is-JavaScript-Used-For.jpg?tx=w_1920,q_auto'],
        title: "Introduction to Web Development",
        description: "Learn the basics of HTML, CSS, and JavaScript to build your first website.",
        media: ['https://bairesdev.mo.cloudinary.net/blog/2023/08/What-Is-JavaScript-Used-For.jpg?tx=w_1920,q_auto'],
        resources: ["https://example.com/resource1.pdf"],
        questions: [],
        marksForPass: 75,
        applicableGrade: 10,
        applicableLevel: 10,
    },
    {
        id: 2,
        thumbnail: ['https://bairesdev.mo.cloudinary.net/blog/2023/08/What-Is-JavaScript-Used-For.jpg?tx=w_1920,q_auto'],
        title: "Fundamentals of Algebra",
        description: "Master the core concepts of algebra with step-by-step explanations.",
        media: ['https://bairesdev.mo.cloudinary.net/blog/2023/08/What-Is-JavaScript-Used-For.jpg?tx=w_1920,q_auto'],
        resources: ["https://example.com/writing-guide.pdf"],
        questions: [],
        marksForPass: 75,
        applicableGrade: 10,
        applicableLevel: 9,
    },
    {
        id: 3,
        thumbnail: ['https://bairesdev.mo.cloudinary.net/blog/2023/08/What-Is-JavaScript-Used-For.jpg?tx=w_1920,q_auto'],
        title: "Basic Python Programming",
        description: "A hands-on course to get started with Python for beginners.",
        media: ['https://bairesdev.mo.cloudinary.net/blog/2023/08/What-Is-JavaScript-Used-For.jpg?tx=w_1920,q_auto'],
        resources: ["https://example.com/py-cheatsheet.pdf"],
        questions: [],
        marksForPass: 80,
        applicableGrade: 10,
        applicableLevel: 11,
    },
    {
        id: 4,
        thumbnail: ['https://bairesdev.mo.cloudinary.net/blog/2023/08/What-Is-JavaScript-Used-For.jpg?tx=w_1920,q_auto'],
        title: "Environmental Science Overview",
        description: "Understand key environmental issues and sustainable solutions.",
        media: ['https://bairesdev.mo.cloudinary.net/blog/2023/08/What-Is-JavaScript-Used-For.jpg?tx=w_1920,q_auto'],
        resources: ["https://example.com/writing-guide.pdf"],
        questions: [],
        marksForPass: 70,
        applicableGrade: 10,
        applicableLevel: 8,
    },
    {
        id: 5,
        thumbnail: ['https://bairesdev.mo.cloudinary.net/blog/2023/08/What-Is-JavaScript-Used-For.jpg?tx=w_1920,q_auto'],
        title: "Introduction to Physics",
        description: "Explore motion, energy, and forces in this beginner physics course.",
        media: ['https://bairesdev.mo.cloudinary.net/blog/2023/08/What-Is-JavaScript-Used-For.jpg?tx=w_1920,q_auto'],
        resources: ["https://example.com/writing-guide.pdf"],
        questions: [],
        marksForPass: 75,
        applicableGrade: 10,
        applicableLevel: 10,
    },
    {
        id: 6,
        thumbnail: ['https://bairesdev.mo.cloudinary.net/blog/2023/08/What-Is-JavaScript-Used-For.jpg?tx=w_1920,q_auto'],
        title: "Creative Writing for Teens",
        description: "Unleash your imagination and improve your writing skills.",
        media: ['https://bairesdev.mo.cloudinary.net/blog/2023/08/What-Is-JavaScript-Used-For.jpg?tx=w_1920,q_auto'],
        resources: ["https://example.com/writing-guide.pdf"],
        questions: [],
        marksForPass: 65,
        applicableGrade: 10,
        applicableLevel: 9,
    },
    {
        id: 7,
        thumbnail: ['https://bairesdev.mo.cloudinary.net/blog/2023/08/What-Is-JavaScript-Used-For.jpg?tx=w_1920,q_auto'],
        title: "Introduction to Chemistry",
        description: "Learn about atoms, elements, and chemical reactions.",
        media: ['https://bairesdev.mo.cloudinary.net/blog/2023/08/What-Is-JavaScript-Used-For.jpg?tx=w_1920,q_auto'],
        resources: ["https://example.com/writing-guide.pdf"],
        questions: [],
        marksForPass: 70,
        applicableGrade: 10,
        applicableLevel: 10,
    },
    {
        id: 8,
        thumbnail: ['https://bairesdev.mo.cloudinary.net/blog/2023/08/What-Is-JavaScript-Used-For.jpg?tx=w_1920,q_auto'],
        title: "History of Ancient Civilizations",
        description: "Discover the rise and fall of great civilizations of the past.",
        media: ['https://bairesdev.mo.cloudinary.net/blog/2023/08/What-Is-JavaScript-Used-For.jpg?tx=w_1920,q_auto'],
        resources: ["https://example.com/history-notes.pdf"],
        questions: [],
        marksForPass: 60,
        applicableGrade: 10,
        applicableLevel: 8,
    },
    {
        id: 9,
        thumbnail: ['https://bairesdev.mo.cloudinary.net/blog/2023/08/What-Is-JavaScript-Used-For.jpg?tx=w_1920,q_auto'],
        title: "Public Speaking Skills",
        description: "Improve your confidence and communication with effective speaking tips.",
        media: ['https://bairesdev.mo.cloudinary.net/blog/2023/08/What-Is-JavaScript-Used-For.jpg?tx=w_1920,q_auto'],
        resources: ["https://example.com/writing-guide.pdf"],
        questions: [],
        marksForPass: 75,
        applicableGrade: 10,
        applicableLevel: 11,
    },
    {
        id: 10,
        thumbnail: ['https://bairesdev.mo.cloudinary.net/blog/2023/08/What-Is-JavaScript-Used-For.jpg?tx=w_1920,q_auto'],
        title: "Beginner Graphic Design",
        description: "Learn how to create stunning visuals using Canva and Figma.",
        media: ['https://bairesdev.mo.cloudinary.net/blog/2023/08/What-Is-JavaScript-Used-For.jpg?tx=w_1920,q_auto'],
        resources: ["https://example.com/design-guide.pdf"],
        questions: [],
        marksForPass: 80,
        applicableGrade: 10,
        applicableLevel: 12,
    },
];
