
export const teachers = [
    {
        "id": 1,
        "image": "https://wallpapers.com/images/hd/beautiful-girls-1920-x-1200-picture-s0l86g6mcnu33rd6.jpg",
        "cover_image": "https://example.com/cover1.jpg",
        "name": "Chathuranga Niroshana",
        "bio": "Login to your accounts to discover grate learning opportunities, and share your achievements",
        "email": "niroshana.c.n.j@gmail.com",
        "password": "hashed_password_here",
        "mobileNo": "0787767237",
        "role": 2,
        "dob": "1990-04-12",
        "score": 19765,
        "level": 12,
        "school_name": "CINEC College",
        "schoolAddressLineOne": "CINEC Campus",
        "city": "Malabe",
        "district": "Hambantota",
        "province": "Southern",
        "sex": 1,
        "created_at": "2025-04-21T10:00:00Z",
        "updatedAt": "2025-04-21T10:00:00Z",
        "is_verified": true,
        "nic": "199029500152",
        "subjectsTaught": ["Mathematics", "Physics"],
        "teachingExperience": "5-7 years"
    },
    {
        "id": 3,
        "image": "https://wallpapers.com/images/hd/beautiful-girls-1920-x-1200-picture-s0l86g6mcnu33rd6.jpg",
        "cover_image": "https://example.com/cover3.jpg",
        "name": "Kasun Fernando",
        "bio": "Login to your accounts to discover grate learning opportunities, and share your achievements",
        "email": "kasun.f@gmail.com",
        "password": "hashed_password_here",
        "mobileNo": "0712345678",
        "role": 2,
        "dob": "1985-09-15",
        "score": 19765,
        "level": 12,
        "school_name": "Ananda College",
        "schoolAddressLineOne": "Maradana",
        "city": "Colombo",
        "district": "Colombo",
        "province": "Western",
        "sex": 1,
        "created_at": "2025-02-21T08:00:00Z",
        "updatedAt": "2025-02-21T08:00:00Z",
        "is_verified": true,
        "nic": "198529800145",
        "subjectsTaught": ["Biology", "Chemistry"],
        "teachingExperience": "10+ years"
    },
    {
        "id": 5,
        "image": "https://wallpapers.com/images/hd/beautiful-girls-1920-x-1200-picture-s0l86g6mcnu33rd6.jpg",
        "cover_image": "https://example.com/cover5.jpg",
        "name": "Dinesh Madushanka",
        "bio": "Login to your accounts to discover grate learning opportunities, and share your achievements",
        "email": "dinesh.m@gmail.com",
        "password": "hashed_password_here",
        "mobileNo": "0769988776",
        "role": 2,
        "dob": "1992-03-05",
        "score": 19765,
        "level": 12,
        "school_name": "Rahula College",
        "schoolAddressLineOne": "Matara",
        "city": "Matara",
        "district": "Matara",
        "province": "Southern",
        "sex": 1,
        "created_at": "2025-04-01T08:30:00Z",
        "updatedAt": "2025-04-01T08:30:00Z",
        "is_verified": true,
        "nic": "199229500189",
        "subjectsTaught": ["Sinhala", "History"],
        "teachingExperience": "3-5 years"
    },
    {
        "id": 7,
        "image": "https://wallpapers.com/images/hd/beautiful-girls-1920-x-1200-picture-s0l86g6mcnu33rd6.jpg",
        "cover_image": "https://example.com/cover7.jpg",
        "name": "Tharindu Gamage",
        "bio": "Login to your accounts to discover grate learning opportunities, and share your achievements",
        "email": "tharindu.g@gmail.com",
        "password": "hashed_password_here",
        "mobileNo": "0710009998",
        "role": 2,
        "dob": "1988-01-24",
        "score": 19765,
        "level": 12,
        "school_name": "Mahanama College",
        "schoolAddressLineOne": "Colombo 3",
        "city": "Colombo",
        "district": "Colombo",
        "province": "Western",
        "sex": 1,
        "created_at": "2025-04-10T09:45:00Z",
        "updatedAt": "2025-04-10T09:45:00Z",
        "is_verified": false,
        "nic": "198829500189",
        "subjectsTaught": ["ICT", "English"],
        "teachingExperience": "5-7 years"
    },
    {
        "id": 9,
        "image": "https://wallpapers.com/images/hd/beautiful-girls-1920-x-1200-picture-s0l86g6mcnu33rd6.jpg",
        "cover_image": "https://example.com/cover10.jpg",
        "name": "Shanika Wijesinghe",
        "bio": "Login to your accounts to discover grate learning opportunities, and share your achievements",
        "email": "shanika.w@gmail.com",
        "password": "hashed_password_here",
        "mobileNo": "0756677889",
        "role": 2,
        "dob": "1983-07-14",
        "score": 19765,
        "level": 12,
        "school_name": "Visakha Vidyalaya",
        "schoolAddressLineOne": "Colombo 5",
        "city": "Colombo",
        "district": "Colombo",
        "province": "Western",
        "sex": 2,
        "created_at": "2025-04-05T07:50:00Z",
        "updatedAt": "2025-04-05T07:50:00Z",
        "is_verified": true,
        "nic": "198329800189",
        "subjectsTaught": ["Science", "Health"],
        "teachingExperience": "10+ years"
    }
]
export const students = [
    {
        "id": 2,
        "image": "https://wallpapers.com/images/hd/beautiful-girls-1920-x-1200-picture-s0l86g6mcnu33rd6.jpg",
        "cover_image": "https://example.com/cover2.jpg",
        "name": "Nimali Perera",
        "bio": "Login to your accounts to discover grate learning opportunities, and share your achievements",
        "email": "nimali.perera@gmail.com",
        "password": "hashed_password_here",
        "mobileNo": "0771234567",
        "role": 1,
        "dob": "2009-06-20",
        "score": 19765,
        "level": 12,
        "school_name": "Royal College",
        "schoolAddressLineOne": "Colombo 7",
        "city": "Colombo",
        "district": "Colombo",
        "province": "Western",
        "sex": 2,
        "created_at": "2025-03-10T10:00:00Z",
        "updatedAt": "2025-03-10T10:00:00Z",
        "is_verified": false,
        "grade": "Grade 10"
    },

    {
        "id": 4,
        "image": "https://wallpapers.com/images/hd/beautiful-girls-1920-x-1200-picture-s0l86g6mcnu33rd6.jpg",
        "cover_image": "https://example.com/cover4.jpg",
        "name": "Sewmini Jayasuriya",
        "bio": "Login to your accounts to discover grate learning opportunities, and share your achievements",
        "email": "sewmini.j@gmail.com",
        "password": "hashed_password_here",
        "mobileNo": "0751122334",
        "role": 1,
        "dob": "2011-12-02",
        "score": 19765,
        "level": 12,
        "school_name": "Hillwood College",
        "schoolAddressLineOne": "Kandy",
        "city": "Kandy",
        "district": "Kandy",
        "province": "Central",
        "sex": 2,
        "created_at": "2025-01-11T09:00:00Z",
        "updatedAt": "2025-01-11T09:00:00Z",
        "is_verified": false,
        "grade": "Grade 8"
    },

    {
        "id": 6,
        "image": "https://wallpapers.com/images/hd/beautiful-girls-1920-x-1200-picture-s0l86g6mcnu33rd6.jpg",
        "cover_image": "https://example.com/cover6.jpg",
        "name": "Ruwani Liyanage",
        "bio": "Login to your accounts to discover grate learning opportunities, and share your achievements",
        "email": "ruwani.l@gmail.com",
        "password": "hashed_password_here",
        "mobileNo": "0745566789",
        "role": 1,
        "dob": "2008-11-18",
        "score": 19765,
        "level": 12,
        "school_name": "Musaeus College",
        "schoolAddressLineOne": "Colombo 7",
        "city": "Colombo",
        "district": "Colombo",
        "province": "Western",
        "sex": 2,
        "created_at": "2025-02-01T11:00:00Z",
        "updatedAt": "2025-02-01T11:00:00Z",
        "is_verified": true,
        "grade": "Grade 11"
    },

    {
        "id": 8,
        "image": "https://wallpapers.com/images/hd/beautiful-girls-1920-x-1200-picture-s0l86g6mcnu33rd6.jpg",
        "cover_image": "https://example.com/cover8.jpg",
        "name": "Dilani Silva",
        "bio": "Login to your accounts to discover grate learning opportunities, and share your achievements",
        "email": "dilani.s@gmail.com",
        "password": "hashed_password_here",
        "mobileNo": "0782233445",
        "role": 1,
        "dob": "2007-04-10",
        "score": 19765,
        "level": 12,
        "school_name": "Sirimavo Bandaranaike Vidyalaya",
        "schoolAddressLineOne": "Colombo",
        "city": "Colombo",
        "district": "Colombo",
        "province": "Western",
        "sex": 2,
        "created_at": "2025-01-15T08:20:00Z",
        "updatedAt": "2025-01-15T08:20:00Z",
        "is_verified": true,
        "grade": "Grade 12"
    },
    {
        "id": 10,
        "image": "https://wallpapers.com/images/hd/beautiful-girls-1920-x-1200-picture-s0l86g6mcnu33rd6.jpg",
        "cover_image": "https://example.com/cover9.jpg",
        "name": "Nipun Lakmal",
        "bio": "Login to your accounts to discover grate learning opportunities, and share your achievements",
        "email": "nipun.lakmal@gmail.com",
        "password": "hashed_password_here",
        "mobileNo": "0777771234",
        "role": 1,
        "dob": "2010-08-29",
        "score": 19765,
        "level": 12,
        "school_name": "Kingswood College",
        "schoolAddressLineOne": "Kandy",
        "city": "Kandy",
        "district": "Kandy",
        "province": "Central",
        "sex": 1,
        "created_at": "2025-03-01T10:15:00Z",
        "updatedAt": "2025-03-01T10:15:00Z",
        "is_verified": false,
        "grade": "Grade 9"
    },

]
